// The dungeon tileset. Every tile is 16x16, drawn by hand, one char per pixel.
// See palette.js for the colour key.

import { T } from '../../shared/constants.js';

export const TILE_ART = {};

// --- floor: near-black stone, faintly speckled ------------------------------
TILE_ART[T.FLOOR] = `
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAABAAAAAAAAAAAA
AABBBAAAAAAAAAAA
AAABAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAABAAAA
AAAAAAAAAABBBAAA
AAAAAAAAAAABAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA`;

// --- patterned floor: a grouted flagstone -----------------------------------
TILE_ART[T.FLOOR_ALT] = `
CCCCCCCCCCCCCCCC
CBBBBBBBBBBBBBBC
CBAAAAAAAAAAAABC
CBAAAAAAAAAAAABC
CBAAAAAAAAAAAABC
CBAAAAAAAAAAAABC
CBAAAAAAAAAAAABC
CBAAAAAAAAAAAABC
CBAAAAAAAAAAAABC
CBAAAAAAAAAAAABC
CBAAAAAAAAAAAABC
CBAAAAAAAAAAAABC
CBAAAAAAAAAAAABC
CBAAAAAAAAAAAABC
CBBBBBBBBBBBBBBC
CCCCCCCCCCCCCCCC`;

// --- sand floor -------------------------------------------------------------
TILE_ART[T.SAND] = `
FFFFFFFFFFFFFFFF
FFFFGFFFFFFFFFFF
FFFFFFFFFFFGFFFF
FFGFFFFFFFFFFFFF
FFFFFFFFFGFFFFFF
FFFFFFFFFFFFFFGF
FGFFFFFFFFFFFFFF
FFFFFFGFFFFFFFFF
FFFFFFFFFFFFFGFF
FFFGFFFFFFFFFFFF
FFFFFFFFFGFFFFFF
FGFFFFFFFFFFFFFF
FFFFFFFFFFFFGFFF
FFFFFGFFFFFFFFFF
FFFFFFFFFFGFFFFF
FFFFFFFFFFFFFFFF`;

// --- cracked floor ----------------------------------------------------------
TILE_ART[T.CRACK] = `
AAAAAAAAAAAAAAAA
AAAAAAAA0AAAAAAA
AAAAAAA0AAAAAAAA
AAAAAA0AAAAAAAAA
AAAAAA0AAAA0AAAA
AAAAA0AAAA0AAAAA
AAAA0AAAA0AAAAAA
AAA0AAAAA0AAAAAA
AAA0AAAAAA0AAAAA
AA0AAAAAAA0AAAAA
AA0AAAAAAAA0AAAA
A0AAAAAAAAA0AAAA
A0AAAAAAAAAA0AAA
AAAAAAAAAAAA0AAA
AAAAAAAAAAAAA0AA
AAAAAAAAAAAAAAAA`;

// --- rubble -----------------------------------------------------------------
TILE_ART[T.RUBBLE] = `
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAVVAAAAAAAAAA
AAAVXXVAAAAVVAAA
AAAVXXVAAAVXXVAA
AAAAVVAAAAVXXVAA
AAAAAAAAAAAVVAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAVVAAAAAAAA
AAVVAVXXVAAAAAAA
AVXXVVXXVAAAVVAA
AVXXVAAVVAAVXXVA
AAVVAAAAAAAAVVAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA`;

// --- dungeon brick wall -----------------------------------------------------
TILE_ART[T.WALL] = `
0000000000000000
0cccccc00cccccc0
0aaaaaa00aaaaaa0
0aaaaab00aaaaab0
0aaaabb00aaaabb0
0abbbbb00abbbbb0
0bbbbbb00bbbbbb0
0000000000000000
ccc00cccccc00ccc
aaa00aaaaaa00aaa
aab00aaaaab00aaa
abb00aaaabb00aaa
bbb00abbbbb00abb
bbb00bbbbbb00bbb
0000000000000000
cccccccccccccccc`;

// --- solid block (also used for the pushable one — they must look alike) ----
TILE_ART[T.BLOCK] = `
0000000000000000
0cccccccccccccc0
0caaaaaaaaaaaab0
0caaaaaaaaaaaab0
0caabbbbbbbbaab0
0caabbbbbbbbaab0
0caabbbbbbbbaab0
0caabbbbbbbbaab0
0caabbbbbbbbaab0
0caabbbbbbbbaab0
0caabbbbbbbbaab0
0caabbbbbbbbaab0
0caaaaaaaaaaaab0
0caaaaaaaaaaaab0
0bbbbbbbbbbbbbb0
0000000000000000`;
TILE_ART[T.PUSH] = TILE_ART[T.BLOCK];

// --- gargoyle statue --------------------------------------------------------
TILE_ART[T.STATUE_L] = `
AAAAAAAAAAAAAAAA
AAAAAAUUUUAAAAAA
AAAAAUVVVVUAAAAA
AAAAUV0VV0VUAAAA
AAAAUVVVVVVUAAAA
AAAAUVXXXXVUAAAA
AAAAAUVVVVUAAAAA
AAAAUUVVVVUUAAAA
AAUVVVVVVVVVVUAA
AAUVVXXXXXXVVUAA
AAUVVXXXXXXVVUAA
AAUVVVVVVVVVVUAA
AAUVXXXXXXXXVUAA
AAUVVVVVVVVVVUAA
AAUUUUUUUUUUUUAA
AAAAAAAAAAAAAAAA`;
TILE_ART[T.STATUE_R] = TILE_ART[T.STATUE_L];

// --- water ------------------------------------------------------------------
TILE_ART[T.WATER] = `
HIIIIIIIHIIIIIII
IIIIIIIIIIIIIIII
IIIJJIIIIIIJJIII
IIJIIJIIIIJIIJII
IIIIIIIIIIIIIIII
IIIIIIIIIIIIIIII
HIIIIIIIHIIIIIII
IIIIIIIIIIIIIIII
IIIIIIIIIIIIIIII
IIIIIIIIIIJJIIII
IIIIIIIIIJIIJIII
IIIIIIIIIIIIIIII
IIJJIIIIIIIIIIII
IJIIJIIIIIIIIIII
IIIIIIIIIIIIIIII
HIIIIIIIHIIIIIII`;

// second water frame — the crests drift one tile over
export const WATER_2 = `
HIIIIIIIHIIIIIII
IIIIIIIIIIIIIIII
IIIIIIIJJIIIIIJJ
IIIIIIJIIJIIIJII
IIIIIIIIIIIIIIII
IIIIIIIIIIIIIIII
HIIIIIIIHIIIIIII
IIIIIIIIIIIIIIII
IIIIIIIIIIIIIIII
IIJJIIIIIIIIIIII
IJIIJIIIIIIIIIII
IIIIIIIIIIIIIIII
IIIIIIIIIIIIJJII
IIIIIIIIIIIJIIJI
IIIIIIIIIIIIIIII
HIIIIIIIHIIIIIII`;

// --- staircase --------------------------------------------------------------
TILE_ART[T.STAIRS] = `
0000000000000000
0UUUUUUUUUUUUUU0
0VVVVVVVVVVVVVV0
0XXXXXXXXXXXXXX0
0UUUUUUUUUUUUUU0
0VVVVVVVVVVVVVV0
0XXXXXXXXXXXXXX0
0UUUUUUUUUUUUUU0
0VVVVVVVVVVVVVV0
0XXXXXXXXXXXXXX0
0UUUUUUUUUUUUUU0
0VVVVVVVVVVVVVV0
0XXXXXXXXXXXXXX0
0UUUUUUUUUUUUUU0
0VVVVVVVVVVVVVV0
0000000000000000`;

// --- altar / dais -----------------------------------------------------------
TILE_ART[T.ALTAR] = `
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAUUUUUUUUUUUUAA
AUVVVVVVVVVVVVUA
AUVXXXXXXXXXXVUA
AUVXVVVVVVVVXVUA
AUVXVVVVVVVVXVUA
AUVXXXXXXXXXXVUA
AUVVVVVVVVVVVVUA
AUUUUUUUUUUUUUUA
AAXXXXXXXXXXXXAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA`;

// The doorway tile itself is drawn by the door renderer, not from art.
TILE_ART[T.DOORWAY] = TILE_ART[T.FLOOR];
